
package com.apollo.apollopharamacy.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "apollopharamacyMedicineFinderService", targetNamespace = "http://www.apollo.com/apollopharamacy/wsdl", wsdlLocation = "file:/F:/ECLIPSE-DEV/TRAINING-CENTER/center1/PROJECTS/pharmacy-app/src/main/webapp/WEB-INF/wsdl/apollopharmacy.wsdl")
public class ApollopharamacyMedicineFinderService
    extends Service
{

    private final static URL APOLLOPHARAMACYMEDICINEFINDERSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.apollo.apollopharamacy.wsdl.ApollopharamacyMedicineFinderService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.apollo.apollopharamacy.wsdl.ApollopharamacyMedicineFinderService.class.getResource(".");
            url = new URL(baseUrl, "file:/F:/ECLIPSE-DEV/TRAINING-CENTER/center1/PROJECTS/pharmacy-app/src/main/webapp/WEB-INF/wsdl/apollopharmacy.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/F:/ECLIPSE-DEV/TRAINING-CENTER/center1/PROJECTS/pharmacy-app/src/main/webapp/WEB-INF/wsdl/apollopharmacy.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        APOLLOPHARAMACYMEDICINEFINDERSERVICE_WSDL_LOCATION = url;
    }

    public ApollopharamacyMedicineFinderService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ApollopharamacyMedicineFinderService() {
        super(APOLLOPHARAMACYMEDICINEFINDERSERVICE_WSDL_LOCATION, new QName("http://www.apollo.com/apollopharamacy/wsdl", "apollopharamacyMedicineFinderService"));
    }

    /**
     * 
     * @return
     *     returns MedicineFinder
     */
    @WebEndpoint(name = "apollopharamacySOAPPort")
    public MedicineFinder getApollopharamacySOAPPort() {
        return super.getPort(new QName("http://www.apollo.com/apollopharamacy/wsdl", "apollopharamacySOAPPort"), MedicineFinder.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MedicineFinder
     */
    @WebEndpoint(name = "apollopharamacySOAPPort")
    public MedicineFinder getApollopharamacySOAPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.apollo.com/apollopharamacy/wsdl", "apollopharamacySOAPPort"), MedicineFinder.class, features);
    }

}
