
package com.apollo.apollopharamacy.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.apollo.apollopharamacy.types.Criteria;
import com.apollo.apollopharamacy.types.MedicineList;
import com.apollo.apollopharamacy.types.ObjectFactory;
import com.apollo.apollopharamacy.types.Store;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "MedicineFinder", targetNamespace = "http://www.apollo.com/apollopharamacy/wsdl")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MedicineFinder {


    /**
     * 
     * @param store
     * @param criteria
     * @return
     *     returns com.apollo.apollopharamacy.types.MedicineList
     */
    @WebMethod(action = "http://www.apollo.com/apollopharamacy/wsdl/search")
    @WebResult(name = "ListOfMedicine", targetNamespace = "http://www.apollo.com/apollopharamacy/types")
    @RequestWrapper(localName = "search", targetNamespace = "http://www.apollo.com/apollopharamacy/types", className = "com.apollo.apollopharamacy.types.Search")
    @ResponseWrapper(localName = "searchResponse", targetNamespace = "http://www.apollo.com/apollopharamacy/types", className = "com.apollo.apollopharamacy.types.SearchResponse")
    public MedicineList search(
        @WebParam(name = "criteria", targetNamespace = "http://www.apollo.com/apollopharamacy/types")
        Criteria criteria,
        @WebParam(name = "store", targetNamespace = "http://www.apollo.com/apollopharamacy/types")
        Store store);

}
